### ISSUE TITLE
[ERROR] :  Error: Requested module not found: com.neverhide.bletransmitter

### ISSUE THREAD

**Issue by bruce-atkinson** [hiddestokvis/TitaniumBeaconTransmitter#3]
I'm a tiapp developer, not a module developer, so I'm sure I'm not doing something right...
I renamed the "android" directory 0.1 and placed it into a new directory named "com.neverhide.bletransmitter", and then put this into my module folder. I then added this to my project's tiapp.xml. 
I called it in my index.js using var AndroidBeacon = require('com.neverhide.bletransmitter');
I get the following errors:
[ERROR] :  Error: Requested module not found: com.neverhide.bletransmitter
[ERROR] :  File: app.js
[ERROR] :  Line: undefined
[ERROR] :  SourceId: undefined
[ERROR] :  Backtrace:
[ERROR] :  undefined
[ERROR] :  TiHTTPClient: (TiHttpClient-10) [636,636] HTTP Error (java.io.IOException): 404 : Not Found
[ERROR] :  TiHTTPClient: java.io.IOException: 404 : Not Found
[ERROR] :  TiHTTPClient:    at ti.modules.titanium.network.TiHTTPClient$ClientRunnable.run(TiHTTPClient.java:1213)
[ERROR] :  TiHTTPClient:    at java.lang.Thread.run(Thread.java:818)

Can you point me in the right direction? Do I need to build the module and if so, how?

**Comment by hiddestokvis** [comment]
@RBAtkins0n I have added a pre-build version to the git repository. The easiest way to add this module to your project is:
1. to download [the release of this module](https://github.com/hiddestokvis/TitaniumBeaconTransmitter/releases/tag/0.9.0)
2. Extract the zip file and find the com.neverhide.bletransmitter-android-0.1.zip file
3. In Appcelerator studio go to Help > Install Mobile Module and select the com.neverhide.bletransmitter-android-0.1.zip file
4. Install the module either directly to your project or globally.
